//
//  VLCAutoGeneratedMenuContent.swift
//  Eriri
//
//  Created by xjbeta on 3/5/21.
//  Copyright © 2021 xjbeta. All rights reserved.
//

import Cocoa

class VLCAutoGeneratedMenuContent: NSObject {
    let name: String
    let value: vlc_value_t
    let object: UnsafeMutablePointer<vlc_object_t>!
    let type: Int
    
    init(_ variableName: String,
         of object: UnsafeMutablePointer<vlc_object_t>!,
         and value: vlc_value_t,
         of type: Int) {
        self.name = variableName
        self.value = value
        self.object = object
        self.type = type
    }
}
